### ISSUE TITLE
Does Not Work

### ISSUE THREAD

**Issue by ew0k** [hkbakke/qubes-wireguard#1]
```
[user@sys-vpn-wireguard ~]$ git clone https://github.com/hkbakke/qubes-wireguard

Cloning into 'qubes-wireguard'...

remote: Enumerating objects: 43, done.

remote: Counting objects: 100% (43/43), done.

remote: Compressing objects: 100% (27/27), done.

remote: Total 43 (delta 20), reused 27 (delta 10), pack-reused 0

Receiving objects: 100% (43/43), 6.51 KiB | 6.51 MiB/s, done.

Resolving deltas: 100% (20/20), done.

[user@sys-vpn-wireguard ~]$ ls

Desktop    Downloads  Pictures  Templates  qubes-wireguard
Documents  Music      Public    Videos

[user@sys-vpn-wireguard ~]$ cd qubes-wireguard

[user@sys-vpn-wireguard qubes-wireguard]$ ls

README.md  bin  config.example

[user@sys-vpn-wireguard qubes-wireguard]$ cp config.example config

[user@sys-vpn-wireguard qubes-wireguard]$ chmod 600 config

[user@sys-vpn-wireguard qubes-wireguard]$ ls

README.md  bin  config  config.example

[user@sys-vpn-wireguard qubes-wireguard]$ sudo ./bin/qubes-wg-conf

[user@sys-vpn-wireguard qubes-wireguard]$ 
```

Here is a copy of my config file (using mullvad)

`WG_ADDRESS="10.64.185.11/32,fc00:bbbb:bbbb:bb01::1:b90a/128"
WG_DNS="193.138.218.74"
WG_PRIVATE_KEY="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX="
WG_PEER_PUBLIC_KEY="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
WG_ENDPOINT="193.138.218.74"`

Attaching a disposableVM's networking to the wireguard App the internet is accessible via original WAN connection (i.e. iP leak).

**Comment by hkbakke** [comment]
The readme leaves out one crucial step: you must restart the VPN qube after running ./bin/qubes-wg-conf. The script does not reload the firewall or the wireguard service, so the changes are not activated until the next boot.

**Comment by ew0k** [comment]
Thanks for the tip. Everything is working now. Thank you for taking time and effort to publish this work. 

Can you consider adding some type of visual feedback notification? (i.e.  link "xx" up, link "xx" down, "link xx failure")

**Comment by hkbakke** [comment]
Thanks, no problem!

With visual feedback, do you mean an icon in the upper right corner where other network status etc. is indicated?

**Comment by hkbakke** [comment]
Also regarding fail safe, it actually handles this as long as it is only used for network provider qubes as documented in the readme, and not as an app qube. If you look closely at the firewall forward rules it only allows traffic from the lan interface flowing to the wireguard interface. That means that if the wireguard interface is down, the traffic flowing from the lan is dropped. This can be verified with tools like tcpdump by taking down the wg tunnel. If you see that this is not the case it is a bug and I will fix it.

There is nothing preventing the VPN qube itself from talking to the WAN if the wireguard tunnel is down, but this is by design and intended from my side. The intention is to make sure the clients behind the VPN qube stays protected even if the tunnel is down.

**Comment by ew0k** [comment]
hkbakke, thank you for taking the time to explain that and update the documentation. 

regarding the visual feedback, i just mean if possible something really simple like a basic notification to let the user know the link is up / down / failure and maybe include some reference to the VM name or wg connection in case the user is running multiple wg vms. An example would be [taskets script ](https://github.com/tasket/Qubes-vpn-support). 

i would like to buy you a dinner as gesture of thanks for time and effort you have gone to publish this and make it available to less technical users like myself. if you have a bitcoin address let me know.

**Comment by hkbakke** [comment]
> 
> 
> hkbakke, thank you for taking the time to explain that and update the documentation.
> 
> regarding the visual feedback, i just mean if possible something really simple like a basic notification to let the user know the link is up / down / failure and maybe include some reference to the VM name or wg connection in case the user is running multiple wg vms. An example would be [taskets script ](https://github.com/tasket/Qubes-vpn-support).
> 
> i would like to buy you a dinner as gesture of thanks for time and effort you have gone to publish this and make it available to less technical users like myself. if you have a bitcoin address let me know.

I appreciate the kind words! No need to do anything. I use this myself, so any input that leads to improved quality in some way is useful enough for me.
