### ISSUE TITLE
will this work with multihop

### ISSUE THREAD

**Issue by rudolfocode** [hkbakke/qubes-wireguard#2]
Great job, works well!

one question, @hkbakke will this work effectively with a multihop wireguard .conf file?

Thanks

**Comment by hkbakke** [comment]
Do you by multi hop mean two tunnels where one tunnel goes within another using two wg configs? If so the current configuration script does not support that use case. It is entirely possible to implement it, but I would rather recommend a two gateway approach instead (i.e. a wireguard gateway behind another), as it will be completely standard, secure and more inline with Qubes workflow in general.

**Comment by rudolfocode** [comment]
Thanks for getting back to me

I managed to get multihop working with a single config file as I'm using mullvad and all of their wireguard servers are connected to each other using tunnels.

Quote from their site:

> Each WireGuard server is connected to all the other WireGuard servers through WireGuard tunnels. This means you can multihop from one server to another. One way to do this is to connect to a specific port on a WireGuard server which will then connect to the other WireGuard server via the tunnel.

> In the WireGuard configuration file the Endpoint port defines the exit server, and the preceding IP-address or hostname defines the entry server: "INSERVER-IP:OUTSERVER-PORT". The PublicKey is that of the exit server.

> For example, let's say you want to connect to nl1 via se4 (so nl1 is the exit server). To do this, you would connect to se4-wireguard.mullvad.net:3004 and use the public key of the nl1 server. The port 3004 is the multihop port for nl1.

> Choose a multihop port from [our server page](https://mullvad.net/servers). Then add a new multihop configuration file by modifying an existing one. In the following example you start with an existing configuration file for nl1 so you have the public key for that. Then you change the Endpoint to connect to se4-wireguard.mullvad.net (or 193.138.218.130) and jump to nl1 via it's multihop port 3004. The configuration is saved as a new configuration file.

[source](https://mullvad.net/en/help/wireguard-and-mullvad-vpn/)

I just wondered if my security could be compromised using this configuration in your wireguard implementation somehow.

**Comment by hkbakke** [comment]
I see. So it's basically just magic forwarding that happens based on which wireguard server port you connect to. As far as I understand you need exactly the same configuration parameters as a normal single hop connection, so this should be just as secure as a normal wireguard configuration with my configuration script.
