### ISSUE TITLE
Incoming connections inside the tunnel

### ISSUE THREAD

**Issue by vlad-tim** [hkbakke/qubes-wireguard#3]
Thank you for the great configuration script.

I was able to set up a chain like this that works well for outgoing connections:

`AppVM => WirequardVM => FirewallVM => NetVM`

However, when I send incoming traffic, it does not reach the destination. Ideally the destination would be inside the `AppVM`, but even when it's inside `WireguardVM` that has IP address `10.9.0.8`, I cannot reach it. More specifically, I can ping other hosts within the VPN network from `AppVM`, such as `10.9.0.6`, but not `WireguardVM` itself. TCP traffic does not come as well.

Do you have an idea how to enable inbound traffic into the WireguardVM? The [official firewall docs](https://www.qubes-os.org/doc/firewall/) have lots of useful information, but it didn't help me to achieve the goal.

**Comment by hkbakke** [comment]
I am not entireliy sure what you mean here. Do you want to initiate connections to the app vm from the VPN server side? Is the use case when an application needs forwarded ports on the VPN server end, or do you want to actually reach the app VM IP for all services from the VPN server side? The first one lives well with NAT so it is just a question of opening up the firewall, but the latter is much more involved and requires routing table updates on the VPN server side in addition to opening up the firewall.

**Comment by vlad-tim** [comment]
Here is a simplification of my use case:

`10.9.0.1` - private IP of the Wireguard server (cloud VM, all VPN clients connect to its public IP).
`10.9.0.6` - private IP of the Client1 (Android phone)
`10.9.0.8` - private IP of the Client2 (Laptop running QubesOS)

Now the goal is to run a web server on Client2 and make it available to Client1. For the beginning, I am trying to run the web server inside the `WireguardVM`, and not `AppVM`, since it seems simpler to configure.

Now the expectation is that I can reach the web server from `Client1` by typing `http://10.9.0.8` in the browser. But that's not the case.

Note: I am able to do it easily if `Client2` is Ubuntu instead of Qubes. I just use `ufw` to allow all incoming traffic within the VPN tunnel, without any configuration changes on the server side.

**Comment by vlad-tim** [comment]
I was able to solve the problem by following [this steps](https://github.com/QubesOS/qubes-issues/issues/6194#issuecomment-750927304) from another github issue.
